// Validation schemas using Zod
import { z } from 'zod';

export const schemas = {
  profileUpdateSchema: z.object({
    name: z.string().optional(),
    roles: z.array(z.string()).optional(),
    bio: z.string().optional(),
    availability: z.string().optional(),
    location: z.string().optional(),
    profileImage: z.string().optional(),
    resumeUrl: z.string().optional(),
  }),

  contactSchema: z.object({
    name: z.string().min(1),
    email: z.string().email(),
    subject: z.string().optional(),
    message: z.string().min(1),
    profession: z.string().optional(),
  }),

  projectCreateSchema: z.object({
    title: z.string().min(1),
    slug: z.string().optional(),
    description: z.string().optional(),
    longDescription: z.string().optional(),
    thumbnail: z.string().optional(),
    videoUrl: z.string().optional(),
    techStack: z.array(z.string()).optional(),
    demoUrl: z.string().optional(),
    githubUrl: z.string().optional(),
    featured: z.boolean().optional(),
    published: z.boolean().optional(),
    order: z.number().optional(),
  }),
  projectUpdateSchema: z.object({
    id: z.string(),
    title: z.string().optional(),
    slug: z.string().optional(),
    description: z.string().optional(),
    longDescription: z.string().optional(),
    thumbnail: z.string().optional(),
    videoUrl: z.string().optional(),
    techStack: z.array(z.string()).optional(),
    demoUrl: z.string().optional(),
    githubUrl: z.string().optional(),
    featured: z.boolean().optional(),
    published: z.boolean().optional(),
    order: z.number().optional(),
  }),

  skillCreateSchema: z.object({
    name: z.string().min(1),
    category: z.string().optional(),
    level: z.number().int().min(0).max(100).optional(),
    icon: z.string().optional(),
    order: z.number().optional(),
    published: z.boolean().optional(),
  }),
  skillUpdateSchema: z.object({
    id: z.string(),
    name: z.string().optional(),
    category: z.string().optional(),
    level: z.number().int().optional(),
    icon: z.string().optional(),
    order: z.number().optional(),
    published: z.boolean().optional(),
  }),

  experienceCreateSchema: z.object({
    role: z.string().optional(),
    company: z.string().optional(),
    logo: z.string().optional(),
    startDate: z.string().optional(),
    endDate: z.string().nullable().optional(),
    responsibilities: z.array(z.string()).optional(),
    techTags: z.array(z.string()).optional(),
    order: z.number().optional(),
  }),
  experienceUpdateSchema: z.object({
    id: z.string(),
    role: z.string().optional(),
    company: z.string().optional(),
    logo: z.string().optional(),
    startDate: z.string().optional(),
    endDate: z.string().nullable().optional(),
    responsibilities: z.array(z.string()).optional(),
    techTags: z.array(z.string()).optional(),
    order: z.number().optional(),
  }),

  educationCreateSchema: z.object({
    degree: z.string().optional(),
    institution: z.string().optional(),
    logo: z.string().optional(),
    startDate: z.string().optional(),
    endDate: z.string().optional(),
    milestones: z.array(z.string()).optional(),
    order: z.number().optional(),
  }),
  educationUpdateSchema: z.object({
    id: z.string(),
    degree: z.string().optional(),
    institution: z.string().optional(),
    logo: z.string().optional(),
    startDate: z.string().optional(),
    endDate: z.string().optional(),
    milestones: z.array(z.string()).optional(),
    order: z.number().optional(),
  }),

  certificationCreateSchema: z.object({
    title: z.string().optional(),
    issuer: z.string().optional(),
    credentialId: z.string().optional(),
    verificationUrl: z.string().optional(),
    thumbnail: z.string().optional(),
    skills: z.array(z.string()).optional(),
    date: z.string().optional(),
    published: z.boolean().optional(),
    order: z.number().optional(),
  }),
  certificationUpdateSchema: z.object({
    id: z.string(),
    title: z.string().optional(),
    issuer: z.string().optional(),
    credentialId: z.string().optional(),
    verificationUrl: z.string().optional(),
    thumbnail: z.string().optional(),
    skills: z.array(z.string()).optional(),
    date: z.string().optional(),
    published: z.boolean().optional(),
    order: z.number().optional(),
  }),

  socialCreateSchema: z.object({
    platform: z.string().min(1),
    url: z.string().url(),
    username: z.string().optional(),
    published: z.boolean().optional(),
    displayOrder: z.number().optional(),
  }),
};
